### PR TITLE
    Solving the problem that RIPE style WHOIS answers need to end with

### LINKED ISSUE #335: response missing double empty line in v4.0.8
The following debug output to a query show a missing empty line at the end of the response from IRRd 4.0.8 (other versions not checked):

There is 1 empty line, but since this separates several RPSL results in the same query, the end of the response is only recognized when seeing 2 empty lines (this is part of the RPSL standard, as I understand it). 

This double empty line is seen from older IRRd versions, for example the one installed at RADB. The bug in 4.0.8 was observed when querying ARIN.

Since any heuristic end-of-response detection is unreliable,  a fix in the fabulous IRRd v4.x would be most welcome.

Thanks for your support!

```
CSIRRD: Open localhost:8043 source=ARIN protocol=csirrd
CSIRRD: Send query [!!
] length= 3
CSIRRD: Send query [!v
] length= 3
CSIRRD: read response chunk 1, len=28
CSIRRD: response chunk 'A22
IRRd -- version 4.0.8
C
'
CSIRRD: Send query [-r -s ARIN -T as-set AS-GAIKAI
] length= 31
CSIRRD: old response [] length= 0
CSIRRD: read response chunk 1, len=388
CSIRRD: response chunk 'as-set:         AS-GAIKAI
descr:          Sony CGEI Global IP Network
descr:          65 Enterprise
descr:          Aliso Viejo, CA 92656
members:        AS33353,AS11795,AS25562,AS13989
members:        AS55901,AS397077,AS397191
tech-c:         ARINA92-ARIN
admin-c:        ARINA92-ARIN
mnt-by:         MNT-GAIKA-1
changed:        christopher.costa@sony.com 20190507
source:         ARIN

'
CSIRRD: read response chunk 2, len=0
CSIRRD: No response for query "-r -s ARIN -T as-set AS-GAIKAI" after 3 seconds; retry 1...
...
```

### PR DESCRIPTION
**Pull request by icing**
Solving the problem that RIPE style WHOIS answers need to end with
    exactly 2 empty lines. While not part of the RPSL RFCs and WHOIS
    per se, this became necessary by continued connection usage (-k).

   Fixes #335 

    The client need to detect the end of a RPSL response, irregardless
    of query and network timings. See also:
    <https://www.ripe.net/manage-ips-and-asns/db/support/documentation/ripe-database-query-reference-manual#2-0-querying-the-ripe-database>

### CODE REVIEW

**Comment by job** [comment]
while the bug seems clear, the code is anything but clear.

Can you rewrite this to not depend on the `re` module? Also not sure if `if s is not None:` is idiomatic.

@mxsasha can you give pointers to the expected coding style or is this PR actually the cleanest way to do it?

**Comment by icing** [comment]
Sorry about the unneccessary re import. Removed.

I have no objections if anyone comes up with a cleaner python solution for this. It just needs to enforce exactly 2 empty lines at the end of the response string, no matter what the response is.

**Comment by job** [comment]
```
>>> s = """test
... 
... """
>>> s
'test\n\n'
>>> s.endswith('\n\n')
True
```

**Comment by icing** [comment]
When I meant `exactly`, it did not mean "4 newlines at the end are also ok". ;-)

**Comment by icing** [comment]
The lastest addition include the fix for #342, verified by successful mirroring the RIPE db in my setup.

**Comment by mxsasha** [comment]
I went with a slightly different fix for #335 in c2ac7e650b315de9e677320f28d51865916d0b81. Since the newlines were already being added, just not always enough, I added it where the current ones are added. I feel it is a bit more readable, but it is bike shedding a bit.
Also, this needed tests and documentation updates.

**Comment by mxsasha** [comment]
The fix for #342 was merged in ef416b24a8f1b6a3e82234c796a2dadc7ae52852 almost as is (file objects are already an iterator, and therefore don't need to be wrapped in iter()).

For future cases, please do put separate issues in separate pull requests :)

Memory usage while doing a full import from RIPE seems to be around 500-900MB now, so that is a dramatic decrease, thanks!

**Comment by icing** [comment]
Thanks for taking this in!

**Pull request closed without merging**
