### PR TITLE
Expose some metrics in Prometheus format

### PR DESCRIPTION
**Pull request by steffann**
At 6connect we wanted to monitor the state of our IRRD using prometheus. Here is an initial implementation, which we would like to contribute back if you want it.

### CODE REVIEW

**Comment by mxsasha** [comment]
Thanks, I think this would be a good addition! Other than that it would need tests and docs, my first concern is how often people would request this from their monitoring setup? The statistics queries can be somewhat heavy, though I haven't measured them specifically. If they are run very frequently, the load can become an issue.

**Comment by steffann** [comment]
A random data point: I'm running them once a minute from Prometheus, and one request takes about 5 seconds on my VM.

I'm using the simple query `irrd_seconds_since_last_update{}` in Grafana to keep an eye on when a source was last updated:

image

You can see exactly when updates are processed :)
And that my APNIC and AFRINIC mirrors are quite out of date…

**Comment by steffann** [comment]
Anyway, what I wanted to say: I'll write tests and docs and will get back to you :)

**Comment by mxsasha** [comment]
@steffann you mentioned that you were still planning to pick this up, any idea on when? :)

**Comment by steffann** [comment]
In the next couple of weeks I expect!

**Comment by steffann** [comment]
Predictions on available time are so unreliable… I'm back on it this week!

**Comment by steffann** [comment]
Ok, improved the code a bit. Rebased it based on 4.5-dev. Added basics documentation.

I don't know how to write a proper test for this though, I could use some help with that…

**Comment by steffann** [comment]
Ok, proper spelling, import order and formatting now :D

**Comment by mxsasha** [comment]
@steffann could you enable ["allow edits from maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on this PR? I can not update it otherwise, as you own the branch.

**Comment by mxsasha** [comment]
Fixed in #882, with tests, some cleanup, and added NRTMv4 serials. Thanks for the work!

**Comment by mxsasha** [comment]
> > The statistics queries can be somewhat heavy, though I haven't measured them specifically. If they are run very frequently, the load can become an issue.
>
> I'm running them once a minute from Prometheus, and one request takes about 5 seconds on my VM.

Screenshot 2024-12-18 at 10 10 33

All this load is prometheus, it's (eyeballing) 70% of IRRDs total IO load on this instance. So perhaps this is too heavy to run once per minute. Alternatively, we could have separate endpoints for mirroring status, which is light and changes rapidly, vs object statistics, which is heavy and changes slowly, but that's more work. (This is a reasonable assumption that I have not measured.)

**Pull request closed without merging**
