### PR TITLE
Limit nrtm serials requesting time

### PR DESCRIPTION
**Pull request by Justin-APNIC**
Add configurable days limit for NRTM query as RIPE

```
% telnet whois.ripe.net 4444
Trying 193.0.6.135...
Connected to whois.ripe.net.
Escape character is '^]'.
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

-g RIPE:3:2278326-2278327
%ERROR:401: (Requesting serials older than 14 days will be rejected)

Connection closed by foreign host.
```

### CODE REVIEW

**Comment by mxsasha** [comment]
It's not exactly the same, but we do have `sources.{name}.nrtm_query_serial_range_limit` which limits the range of serials. I chose that metric because it more directly translates to load, and basing it on timestamp is a bit more tricky. Specifically, the check itself should be very light in terms of query load. Although the original reason for adding that setting was fixed in #774.

Your current PR will fail if the starting serial is missing from the journal, which can happen. IRRD generates sequential serials itself, but serials from others have gaps.

**Comment by Justin-APNIC** [comment]
>Your current PR will fail if the starting serial is missing from the journal, which can happen. IRRD generates sequential serials itself, but serials from others have gaps.

Thanks for the reply. Actually, if the starting serial doesn't exist in the journal table, the query will fail on https://github.com/irrdnet/irrd/blob/main/irrd/mirroring/nrtm_generator.py#L52 first. My newly added codes won't be triggered.

**Comment by mxsasha** [comment]
> > Your current PR will fail if the starting serial is missing from the journal, which can happen. IRRD generates sequential serials itself, but serials from others have gaps.
> 
> Thanks for the reply. Actually, if the starting serial doesn't exist in the journal table, the query will fail on https://github.com/irrdnet/irrd/blob/main/irrd/mirroring/nrtm_generator.py#L52 first. My newly added codes won't be triggered.

No, because that checks for a range. The requested start serial may still not exist, as long as it is not older than the oldest serial. So you might have:

* Serial 10, 25 days ago
* Serial 15, 20 days ago
* Serial 20, 5 days ago

If the user requests serial 8 or 9-LAST, it is currently rejected by the line you linked. If they request 12-LAST, the query is currently accepted and the response will have serial 15 and 20. Your code will try to look up serial 12 in the journal which does not exist in the journal.

I have explored this when I implemented `nrtm_query_serial_range_limit`, because I also wanted a limit on the age first, but found the serial gaps made it impractical. Of course, we could check for "the timestamp of the the oldest journal entry that is within the requested serial range". I'm pretty sure I ran into another problem there though, possibly performance of that SQL query. When the purpose of this restriction was to limit load on the server, so it should be fast and light to check.

**Comment by Justin-APNIC** [comment]
> > > Your current PR will fail if the starting serial is missing from the journal, which can happen. IRRD generates sequential serials itself, but serials from others have gaps.
> > 
> > 
> > Thanks for the reply. Actually, if the starting serial doesn't exist in the journal table, the query will fail on https://github.com/irrdnet/irrd/blob/main/irrd/mirroring/nrtm_generator.py#L52 first. My newly added codes won't be triggered.
> 
> No, because that checks for a range. The requested start serial may still not exist, as long as it is not older than the oldest serial. So you might have:
> 
> * Serial 10, 25 days ago
> * Serial 15, 20 days ago
> * Serial 20, 5 days ago
> 
> If the user requests serial 8 or 9-LAST, it is currently rejected by the line you linked. If they request 12-LAST, the query is currently accepted and the response will have serial 15 and 20. Your code will try to look up serial 12 in the journal which does not exist in the journal.
> 
> I have explored this when I implemented `nrtm_query_serial_range_limit`, because I also wanted a limit on the age first, but found the serial gaps made it impractical. Of course, we could check for "the timestamp of the the oldest journal entry that is within the requested serial range". I'm pretty sure I ran into another problem there though, possibly performance of that SQL query. When the purpose of this restriction was to limit load on the server, so it should be fast and light to check.

Thanks for the clarification.  I think we can fetch the records greater than or equal to the requested start serial, then use the first record which is the oidest jounal entry to check.  See my latest [commit](https://github.com/irrdnet/irrd/pull/842/commits/7de14d1cf5c2e557dbfada25474b0ec6ab2ea01d) 

Sql is like `select * from rpsl_database_journal where source='TEST' and serial_nrtm >= 12 limit 1;` so the serial 15 entry is returned. As it is older than 14 days, the new error will be returned. I think this sql won't have any performance issue based on my testing using APNIC source mirroring data. How do you think?

**Pull request merged**
