### PR TITLE
Add irt and organisation objects

### PR DESCRIPTION
**Pull request by Justin-APNIC**
Add missing RPSL object types in IRRD for supporting mirroring

### CODE REVIEW

**Comment by mxsasha** [comment]
Yes, we can add these types, but I'm thinking they should probably be optional, or at least easy to disable, as this will affect existing authoritative databases. #496 is probably the best way for that.

**Comment by Justin-APNIC** [comment]
> Yes, we can add these types, but I'm thinking they should probably be optional, or at least easy to disable, as this will affect existing authoritative databases. #496 is probably the best way for that.

Hi, i had a look at the `compatibility.inetnum_search_disabled` and it looks like for improving the prefix query performance. Could you please elaborate how adding those new object types will affect the existing authoritative databases? Thanks.

**Comment by mxsasha** [comment]
> Hi, i had a look at the `compatibility.inetnum_search_disabled` and it looks like for improving the prefix query performance. Could you please elaborate how adding those new object types will affect the existing authoritative databases? Thanks.

Yes, inetnum_search_disabled is a performance thing, but #496 is a suggestion to limit the object classes of objects that users can create in authoritative databases. Providing no authentication changes, anyone with a valid mntner can currently create an inetnum. So #496 is a proposal to restrict that, which I think is useful.

With this PR, the same applies to irt and organisation: in any auth database, any valid mntner could then create these objects, without an ability for the operator to restrict this, hence creating a forced change. It seems reasonable to me for #496 to be fixed first, so that this PR does not cause behaviour change unnecessarily.

**Comment by Justin-APNIC** [comment]
> > Hi, i had a look at the `compatibility.inetnum_search_disabled` and it looks like for improving the prefix query performance. Could you please elaborate how adding those new object types will affect the existing authoritative databases? Thanks.
> 
> Yes, inetnum_search_disabled is a performance thing, but #496 is a suggestion to limit the object classes of objects that users can create in authoritative databases. Providing no authentication changes, anyone with a valid mntner can currently create an inetnum. So #496 is a proposal to restrict that, which I think is useful.
> 
> With this PR, the same applies to irt and organisation: in any auth database, any valid mntner could then create these objects, without an ability for the operator to restrict this, hence creating a forced change. It seems reasonable to me for #496 to be fixed first, so that this PR does not cause behaviour change unnecessarily.

Hi Sasha, I created a mr for this. see https://github.com/irrdnet/irrd/pull/859 thanks

**Pull request merged**
